### ISSUE TITLE
Export misbehaves when PVCs are in PV pending state during export

### ISSUE THREAD

**Issue by kingdonb** [tmattausch/k8s-cluster-export#1]
When PVC is pv pending during export, "pv_null" yaml file is included in export and yq errors are printed in stderr and stdout.  I understand from reading the script that it's intended to grab some PV data along with every PVC, so that resources can be safely detached and reattached.  For my pending PVs, this may not be possible.

I'm not sure what I should expect to happen, because my cluster is basically in an error state before I started the export.  Several PVs are currently Pending on my cluster for some time, and due to some provider mismatch likely won't be fulfilled.  The resulting script behavior is probably as good as can be expected in the circumstances.

I planned to export and try again on another cluster, or fill out the PV with data from my cloud provider and try to reattach the orphaned PVs by hand.  The k8s-cluster-export output was just a little bit less than tolerant of this error state, lots of this:

```
09:19:16 main [ERRO] asked to process document index 0 but there are only 0 document(s)
Error: asked to process document index 0 but there are only 0 document(s)
Usage:
  yq delete [yaml_file] [path] [flags]

Aliases:
  delete, d
```

but, the script execution was not terminated, proceeded through the remaining resources including several deployments that I had, and finally completed successfully.  There was not any harm I could see, other than a couple hundred lines of spurious yq error output, that grabbed my attention and alerted me to the error.  Maybe that's exactly what should happen.

As you perhaps expected, or maybe not, when the PVC is exported without a PV bound to it, an empty file is written into `namespace/2_pv/pv_null.yaml`.  That is not really going to harm anything, but is spurious and probably shouldn't have been written as part of the export.

**Comment by tmattausch** [comment]
Hi Kingdon,

Thanks for the input, yes that is true and not so nice. I implemented two small improvements which should address  this:

- add ```set -e``` and stop the script if such problems occure [(commit)](https://github.com/tmattausch/k8s-cluster-export/commit/26c9587e0ca906e16a4224d14880cfa5fe090c95)
- ignore empty values and null values in the export in general  [commit](https://github.com/tmattausch/k8s-cluster-export/commit/72ccd4b5b0163ca01a66e1be990e1df1c974a374)

Can you test if the script is running smoothly in in the new version?

**Comment by kingdonb** [comment]
Thanks.  I've been adding my own changes as well, since I have some labels and annotations I want to discard that probably most people probably won't care about (related to flux-cd), last-applied-configuration, and some others like generation numbers, anything that looks like noise.

I actually don't have a broken cluster to replicate it on anymore, as I deleted the namespace and moved on after reporting.  But those sound like good changes that will address the issues I was having!
